config/routes.rb
Rails3::Application.routes.draw do

  resources :personaldatas

  resources :months

  resources :products

  resources :calls

  resources :standared_visits

  resources :msrplanners

  resources :tour_programs

  resources :headquators

  resources :places

  namespace :admin do resources :classifydoctors end

  resources :classifydoctors

  resources :doctors

  resources :towns

  namespace :admin do resources :doctors end

  namespace :admin do resources :towns end

  get "about/index"

  namespace :admin do resources :companies end

  devise_for :users, :controllers => { :sessions => "user_sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles

  resources :users do
     member do
       get :edit_password 
       get :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end

  resources :announcements
  
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    resources :settings 
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }
    resources :announcements
    resources :commits
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email        
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end
  end
  

  root :to => "dashboard#index"
  

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  scope :active, lambda { 
    where("starts_at <= ? AND ends_at >= ?", Time.now.utc, Time.now.utc) 
  }    
  scope :since, lambda { |hide_time|  
    where("updated_at > ? OR starts_at > ?", hide_time.utc, hide_time.utc) if hide_time
  }
  
  def self.display(hide_time)
    active.since(hide_time)
  end

end

app/models/call.rb
class Call < ActiveRecord::Base
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

app/models/headquator.rb
class Headquator < ActiveRecord::Base
end

app/models/month.rb
class Month < ActiveRecord::Base
end

app/models/msrplanner.rb
class Msrplanner < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :doctor
end

app/models/personaldata.rb
class Personaldata < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # These fields in a profile are private, and will not be shown to other users.
  PRIVATE_FIELDS = ["id", "created_at", "updated_at", "user_id"]
  
  # TODO: Add validations, if you require any for the profile fields
  
  belongs_to :user
  
  # Filter out the private attributes
  def public_attributes
    self.attribute_names.select{|a| !Profile::PRIVATE_FIELDS.include?(a)}
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  validate :name, :presence => true, :on => :create, :message => "can't be blank"
  
  def self.admin
    @@admin ||= find_by_name("admin")
  end
  
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validate :label, :uniqueness => true, :presence => true
  validates_uniqueness_of :identifier
  
  # Story any kind of object in the value field.
  # This is nice, but you should also make it editable through admin/settings
  serialize :value
  
  def self.load(identifier)
    identifier = identifier.to_s if identifier.is_a?(Symbol)
    
    find_by_identifier(identifier)
  end
  
  # Return the value for a setting
  def self.get(identifier)
    identifier = identifier.to_s if identifier.is_a?(Symbol)
    
    begin
      setting = find_by_identifier(identifier)
    rescue
      setting = nil
    end
    
    setting.nil? ? "" : setting.value
  end
end

app/models/tour_program.rb
class TourProgram < ActiveRecord::Base
  belongs_to :place
  belongs_to :headquator
end

app/models/town.rb
class Town < ActiveRecord::Base
end

app/models/user.rb
require 'aasm_roles'
class User < ActiveRecord::Base
  include AasmRoles
  
  devise :database_authenticatable, :recoverable, :registerable, :rememberable

  # Relations
  has_and_belongs_to_many :roles
  has_one :profile
  
  # Hooks
  after_create :create_profile, :register!
  
  attr_accessible :login, :email, :name, :password, :password_confirmation, :identity_url

  before_validation(:set_default, :on => :create)
  
  def admin?
    has_role?(:admin)
  end
  
  def has_role?(role)
    role_symbols.include?(role.to_sym) || role_symbols.include?(:admin)
  end
  
  def role_symbols
    @role_symbols ||= roles.map {|r| r.name.underscore.to_sym }
  end

  def openid_login?
    !identity_url.blank? #|| (AppConfig.enable_facebook_auth && !facebook_id.blank?)
  end

  def twitter_login?
    !twitter_token.blank? && !twitter_secret.blank?
  end
  
  def not_using_openid?
    !openid_login?
  end
  
  def normalize_identity_url
    self.identity_url = OpenIdAuthentication.normalize_url(identity_url) if openid_login?
  rescue
    errors.add_to_base("Invalid OpenID URL")
  end
  
  def self.find_for_authentication(conditions)
    conditions = ["login = ? or email = ?", conditions[authentication_keys.first], conditions[authentication_keys.first]]
    # raise StandardError, conditions.inspect
    super
  end  

  protected


  def password_required?
    return false if openid_login?
    return false if twitter_login?
    (encrypted_password.blank? || !password.blank?)
  end

  
  def create_profile
    # Give the user a profile
    self.profile = Profile.create    
  end
  
  private
  
  def set_default

  end
  
end

app/controllers/tour_programs_controller.rb
class TourProgramsController < ApplicationController
  # GET /tour_programs
  # GET /tour_programs.xml
  def index
    @tour_programs = TourProgram.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tour_programs }
    end
  end

  # GET /tour_programs/1
  # GET /tour_programs/1.xml
  def show
    @tour_program = TourProgram.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tour_program }
    end
  end

  # GET /tour_programs/new
  # GET /tour_programs/new.xml
  def new
    @tour_program = TourProgram.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tour_program }
    end
  end

  # GET /tour_programs/1/edit
  def edit
    @tour_program = TourProgram.find(params[:id])
  end

  # POST /tour_programs
  # POST /tour_programs.xml
  def create
    @tour_program = TourProgram.new(params[:tour_program])

    respond_to do |format|
      if @tour_program.save
        format.html { redirect_to(@tour_program, :notice => 'Tour program was successfully created.') }
        format.xml  { render :xml => @tour_program, :status => :created, :location => @tour_program }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tour_program.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tour_programs/1
  # PUT /tour_programs/1.xml
  def update
    @tour_program = TourProgram.find(params[:id])

    respond_to do |format|
      if @tour_program.update_attributes(params[:tour_program])
        format.html { redirect_to(@tour_program, :notice => 'Tour program was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tour_program.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tour_programs/1
  # DELETE /tour_programs/1.xml
  def destroy
    @tour_program = TourProgram.find(params[:id])
    @tour_program.destroy

    respond_to do |format|
      format.html { redirect_to(tour_programs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/tour_programs_helper.rb
module TourProgramsHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/tour_programs/_form.html.erb
<%= form_for(@tour_program) do |f| %>
  <% if @tour_program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour_program.errors.count, "error") %> prohibited this tour_program from being saved:</h2>

      <ul>
      <% @tour_program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place %><br />
    <%= f.collection_select :place_id, Place.all, :id, :place %>
  </div>
  <div class="field">
    <%= f.label :headquator %><br />
    <%= f.collection_select :headquator_id, Headquator.all, :id, :head_quator %>
  </div>
  <div class="field">
    <%= f.label :distances %><br />
    <%= f.text_field :distances %>
  </div>
  <div class="field">
    <%= f.label :fare %><br />
    <%= f.text_field :fare %>
  </div>
  <div class="field">
    <%= f.label :no_of_doctors %><br />
    <%= f.text_field :no_of_doctors %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tour_programs/backupindex.html.erb
<h1>Listing tour_programs</h1>

<table>
  <tr>
    <th>Place</th>
    <th>Headquator</th>
    <th>Distances</th>
    <th>Fare</th>
    <th>No of doctors</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tour_programs.each do |tour_program| %>
  <tr>
    <td><%= tour_program.place %></td>
    <td><%= tour_program.headquator %></td>
    <td><%= tour_program.distances %></td>
    <td><%= tour_program.fare %></td>
    <td><%= tour_program.no_of_doctors %></td>
    <td><%= link_to 'Show', tour_program %></td>
    <td><%= link_to 'Edit', edit_tour_program_path(tour_program) %></td>
    <td><%= link_to 'Destroy', tour_program, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tour program', new_tour_program_path %>

app/views/tour_programs/edit.html.erb
<h1>Editing tour_program</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour_program %> |
<%= link_to 'Back', tour_programs_path %>

app/views/tour_programs/index.html.erb
<html> 
<head> 
</head> 
<body> 
<h1>Listing tour_programs</h1>
<center> 
<table border=0>
<tr> 
  <td width="150" height="15" align=left >Name :</td> 
  <td width="300" height="15" align=center ></td> 
  <td width="100" height="15" align=center ><td> 
  <td width="150" height="15" align=center ></td> 
  <td width="150" height="15" align=left >H.Q. :</td> 
  <td width="200" height="15" align=center ></td> 
</tr> 
</table>
<table border=1> 
<tr> 
  <td width="150" height="15" align=center ></td> 
  <td width="300" height="15" align=center >Place</td> 
  <td width="100" height="15" align=center >HQ<br/>EX.BQ<br/>Out stn.</td> 
  <td width="150" height="15" align=center >Distance from<br/>HQ / Out stn.<br/>(one way)</td> 
  <td width="150" height="15" align=center >Fare<br/>(as per<br/>Travel Policy)</td> 
  <td width="200" height="15" align=center >No. of Doctors</td> 
</tr> 
<% faretotal=0 %>
<% doctotal=0 %>
<% @tour_programs.each_with_index do |tour_program,index| %>
  <tr>
    <td width="150" height="15" align=center ><%= index+1 %>
    <td width="150" height="15" align=center><%= tour_program.place.place %></td>
    <td width="150" height="15" align=center><%= tour_program.headquator.head_quator %></td>
    <td width="150" height="15" align=center><%= tour_program.distances %></td>
    <td width="150" height="15" align=center><%= tour_program.fare %></td>
    <td width="150" height="15" align=center><%= tour_program.no_of_doctors %></td>
    <td><%= link_to 'Show', tour_program %></td>
    <td><%= link_to 'Edit', edit_tour_program_path(tour_program) %></td>
    <td><%= link_to 'Destroy', tour_program, :confirm => 'Are you sure?', :method => :delete %></td>
    <% faretotal=faretotal+tour_program.fare.to_i %>
    <% doctotal=doctotal+tour_program.no_of_doctors.to_i %>
  </tr>
<% end %>
<tr> 
  <td width="150" height="60" align=left colspan=3 rowspan=2 >AM's Signature :</br>RM's Signature :</td> 
  <td width="150" height="15" align=center >Total</td> 
  <td width="150" height="15" align=center ><%= faretotal %></td> 
  <td width="200" height="15" align=center ><%= doctotal %></td> 
</tr> 
<tr>
<td width="150" height="15" align=left colspan=3 rowspan=2 >SM's Signature :</td> 
</tr>
</table>
</body> 
</html>
<%= link_to 'New Tour program', new_tour_program_path %>

app/views/tour_programs/new.html.erb
<h1>New tour_program</h1>

<%= render 'form' %>

<%= link_to 'Back', tour_programs_path %>

app/views/tour_programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Place:</b>
  <%= @tour_program.place.place%>
</p>

<p>
  <b>Headquator:</b>
  <%= @tour_program.headquator.head_quator %>
</p>

<p>
  <b>Distances:</b>
  <%= @tour_program.distances %>
</p>

<p>
  <b>Fare:</b>
  <%= @tour_program.fare %>
</p>

<p>
  <b>No of doctors:</b>
  <%= @tour_program.no_of_doctors %>
</p>


<%= link_to 'Edit', edit_tour_program_path(@tour_program) %> |
<%= link_to 'Back', tour_programs_path %>