config/routes.rb
Rails3::Application.routes.draw do

  resources :personaldatas

  resources :months

  resources :products

  resources :calls

  resources :standared_visits

  resources :msrplanners

  resources :tour_programs

  resources :headquators

  resources :places

  namespace :admin do resources :classifydoctors end

  resources :classifydoctors

  resources :doctors

  resources :towns

  namespace :admin do resources :doctors end

  namespace :admin do resources :towns end

  get "about/index"

  namespace :admin do resources :companies end

  devise_for :users, :controllers => { :sessions => "user_sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles

  resources :users do
     member do
       get :edit_password 
       get :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end

  resources :announcements
  
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    resources :settings 
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }
    resources :announcements
    resources :commits
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email        
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end
  end
  

  root :to => "dashboard#index"
  

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/company.rb
class Admin::Company < ActiveRecord::Base
has_many :doctors
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  scope :active, lambda { 
    where("starts_at <= ? AND ends_at >= ?", Time.now.utc, Time.now.utc) 
  }    
  scope :since, lambda { |hide_time|  
    where("updated_at > ? OR starts_at > ?", hide_time.utc, hide_time.utc) if hide_time
  }
  
  def self.display(hide_time)
    active.since(hide_time)
  end

end

app/models/call.rb
class Call < ActiveRecord::Base
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

app/models/headquator.rb
class Headquator < ActiveRecord::Base
end

app/models/month.rb
class Month < ActiveRecord::Base
end

app/models/msrplanner.rb
class Msrplanner < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :doctor
end

app/models/personaldata.rb
class Personaldata < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # These fields in a profile are private, and will not be shown to other users.
  PRIVATE_FIELDS = ["id", "created_at", "updated_at", "user_id"]
  
  # TODO: Add validations, if you require any for the profile fields
  
  belongs_to :user
  
  # Filter out the private attributes
  def public_attributes
    self.attribute_names.select{|a| !Profile::PRIVATE_FIELDS.include?(a)}
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  validate :name, :presence => true, :on => :create, :message => "can't be blank"
  
  def self.admin
    @@admin ||= find_by_name("admin")
  end
  
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validate :label, :uniqueness => true, :presence => true
  validates_uniqueness_of :identifier
  
  # Story any kind of object in the value field.
  # This is nice, but you should also make it editable through admin/settings
  serialize :value
  
  def self.load(identifier)
    identifier = identifier.to_s if identifier.is_a?(Symbol)
    
    find_by_identifier(identifier)
  end
  
  # Return the value for a setting
  def self.get(identifier)
    identifier = identifier.to_s if identifier.is_a?(Symbol)
    
    begin
      setting = find_by_identifier(identifier)
    rescue
      setting = nil
    end
    
    setting.nil? ? "" : setting.value
  end
end

app/models/tour_program.rb
class TourProgram < ActiveRecord::Base
  belongs_to :place
  belongs_to :headquator
end

app/models/town.rb
class Town < ActiveRecord::Base
end

app/models/user.rb
require 'aasm_roles'
class User < ActiveRecord::Base
  include AasmRoles
  
  devise :database_authenticatable, :recoverable, :registerable, :rememberable

  # Relations
  has_and_belongs_to_many :roles
  has_one :profile
  
  # Hooks
  after_create :create_profile, :register!
  
  attr_accessible :login, :email, :name, :password, :password_confirmation, :identity_url

  before_validation(:set_default, :on => :create)
  
  def admin?
    has_role?(:admin)
  end
  
  def has_role?(role)
    role_symbols.include?(role.to_sym) || role_symbols.include?(:admin)
  end
  
  def role_symbols
    @role_symbols ||= roles.map {|r| r.name.underscore.to_sym }
  end

  def openid_login?
    !identity_url.blank? #|| (AppConfig.enable_facebook_auth && !facebook_id.blank?)
  end

  def twitter_login?
    !twitter_token.blank? && !twitter_secret.blank?
  end
  
  def not_using_openid?
    !openid_login?
  end
  
  def normalize_identity_url
    self.identity_url = OpenIdAuthentication.normalize_url(identity_url) if openid_login?
  rescue
    errors.add_to_base("Invalid OpenID URL")
  end
  
  def self.find_for_authentication(conditions)
    conditions = ["login = ? or email = ?", conditions[authentication_keys.first], conditions[authentication_keys.first]]
    # raise StandardError, conditions.inspect
    super
  end  

  protected


  def password_required?
    return false if openid_login?
    return false if twitter_login?
    (encrypted_password.blank? || !password.blank?)
  end

  
  def create_profile
    # Give the user a profile
    self.profile = Profile.create    
  end
  
  private
  
  def set_default

  end
  
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  # GET /admin/companies
  # GET /admin/companies.xml
  def index
    @admin_companies = Admin::Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_companies }
    end
  end

  # GET /admin/companies/1
  # GET /admin/companies/1.xml
  def show
    @admin_company = Admin::Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_company }
    end
  end

  # GET /admin/companies/new
  # GET /admin/companies/new.xml
  def new
    @admin_company = Admin::Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_company }
    end
  end

  # GET /admin/companies/1/edit
  def edit
    @admin_company = Admin::Company.find(params[:id])
  end

  # POST /admin/companies
  # POST /admin/companies.xml
  def create
    @admin_company = Admin::Company.new(params[:admin_company])

    respond_to do |format|
      if @admin_company.save
        format.html { redirect_to(@admin_company, :notice => 'Company was successfully created.') }
        format.xml  { render :xml => @admin_company, :status => :created, :location => @admin_company }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/companies/1
  # PUT /admin/companies/1.xml
  def update
    @admin_company = Admin::Company.find(params[:id])

    respond_to do |format|
      if @admin_company.update_attributes(params[:admin_company])
        format.html { redirect_to(@admin_company, :notice => 'Company was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/companies/1
  # DELETE /admin/companies/1.xml
  def destroy
    @admin_company = Admin::Company.find(params[:id])
    @admin_company.destroy

    respond_to do |format|
      format.html { redirect_to(admin_companies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/admin/companies/_form.html.erb
<%= form_for(@admin_company) do |f| %>
  <% if @admin_company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_company.errors.count, "error") %> prohibited this admin_company from being saved:</h2>

      <ul>
      <% @admin_company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/companies/backupindex.html.erb
<% content_for :header do -%>
	Company
<% end -%>

<h1>Listing admin_companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_companies.each do |admin_company| %>
  <tr>
    <td><%= admin_company.name %></td>
    <td><%= link_to 'Show', admin_company_path(admin_company) %></td>
    <td><%= link_to 'Edit', edit_admin_company_path(admin_company) %></td>
    <td><%= link_to 'Destroy', admin_company, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_admin_company_path %>

app/views/admin/companies/edit.html.erb
<h1>Editing admin_company</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_company %> |
<%= link_to 'Back', admin_companies_path %>

app/views/admin/companies/index.html.erb
<% content_for :header do -%>
	Company
<% end -%>

<h1>Listing admin_companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_companies.each do |admin_company| %>
  <tr>
    <td><%= admin_company.name %></td>
    <td><%= link_to 'Show', admin_company_path(admin_company) %></td>
    <td><%= link_to 'Edit', edit_admin_company_path(admin_company) %></td>
    <td><%= link_to 'Destroy', admin_company, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_admin_company_path %>

app/views/admin/companies/new.html.erb
<h1>New admin_company</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_companies_path %>

app/views/admin/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_company.name %>
</p>


<%= link_to 'Edit', edit_admin_company_path(@admin_company) %> |
<%= link_to 'Back', admin_companies_path %>