config/routes.rb
Rails3::Application.routes.draw do

  resources :personaldatas

  resources :months

  resources :products

  resources :calls

  resources :standared_visits

  resources :msrplanners

  resources :tour_programs

  resources :headquators

  resources :places

  namespace :admin do resources :classifydoctors end

  resources :classifydoctors

  resources :doctors

  resources :towns

  namespace :admin do resources :doctors end

  namespace :admin do resources :towns end

  get "about/index"

  namespace :admin do resources :companies end

  devise_for :users, :controllers => { :sessions => "user_sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles

  resources :users do
     member do
       get :edit_password 
       get :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end

  resources :announcements
  
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    resources :settings 
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }
    resources :announcements
    resources :commits
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email        
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end
  end
  

  root :to => "dashboard#index"
  

end

app/models/admin/town.rb
class Admin::Town < ActiveRecord::Base
has_many :company
end

app/models/town.rb
class Town < ActiveRecord::Base
end

app/controllers/admin/towns_controller.rb
class Admin::TownsController < ApplicationController
  # GET /admin/towns
  # GET /admin/towns.xml
  def index
    @admin_towns = Admin::Town.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_towns }
    end
  end

  # GET /admin/towns/1
  # GET /admin/towns/1.xml
  def show
    @admin_town = Admin::Town.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_town }
    end
  end

  # GET /admin/towns/new
  # GET /admin/towns/new.xml
  def new
    @admin_town = Admin::Town.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_town }
    end
  end

  # GET /admin/towns/1/edit
  def edit
    @admin_town = Admin::Town.find(params[:id])
  end

  # POST /admin/towns
  # POST /admin/towns.xml
  def create
    @admin_town = Admin::Town.new(params[:admin_town])

    respond_to do |format|
      if @admin_town.save
        format.html { redirect_to(@admin_town, :notice => 'Town was successfully created.') }
        format.xml  { render :xml => @admin_town, :status => :created, :location => @admin_town }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_town.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/towns/1
  # PUT /admin/towns/1.xml
  def update
    @admin_town = Admin::Town.find(params[:id])

    respond_to do |format|
      if @admin_town.update_attributes(params[:admin_town])
        format.html { redirect_to(@admin_town, :notice => 'Town was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_town.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/towns/1
  # DELETE /admin/towns/1.xml
  def destroy
    @admin_town = Admin::Town.find(params[:id])
    @admin_town.destroy

    respond_to do |format|
      format.html { redirect_to(admin_towns_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  # GET /towns
  # GET /towns.xml
  def index
    @towns = Town.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @towns }
    end
  end

  # GET /towns/1
  # GET /towns/1.xml
  def show
    @town = Town.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @town }
    end
  end

  # GET /towns/new
  # GET /towns/new.xml
  def new
    @town = Town.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @town }
    end
  end

  # GET /towns/1/edit
  def edit
    @town = Town.find(params[:id])
  end

  # POST /towns
  # POST /towns.xml
  def create
    @town = Town.new(params[:town])

    respond_to do |format|
      if @town.save
        format.html { redirect_to(@town, :notice => 'Town was successfully created.') }
        format.xml  { render :xml => @town, :status => :created, :location => @town }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @town.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /towns/1
  # PUT /towns/1.xml
  def update
    @town = Town.find(params[:id])

    respond_to do |format|
      if @town.update_attributes(params[:town])
        format.html { redirect_to(@town, :notice => 'Town was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @town.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /towns/1
  # DELETE /towns/1.xml
  def destroy
    @town = Town.find(params[:id])
    @town.destroy

    respond_to do |format|
      format.html { redirect_to(towns_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/towns_helper.rb
module Admin::TownsHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/admin/towns/_form.html.erb
<%= form_for(@admin_town) do |f| %>
  <% if @admin_town.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_town.errors.count, "error") %> prohibited this admin_town from being saved:</h2>

      <ul>
      <% @admin_town.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :town %><br />
    <%= f.text_field :town %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/towns/edit.html.erb
<h1>Editing admin_town</h1>
<h2>testing</h2>

<%= render 'form' %>

<%= link_to 'Show', @admin_town %> |
<%= link_to 'Back', admin_towns_path %>

app/views/admin/towns/index.html.erb
<h1>Listing admin_towns</h1>

<table>
  <tr>
    <th>Town</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_towns.each do |admin_town| %>
  <tr>
    <td><%= admin_town.town %></td>
    <td><%= link_to 'Show', admin_town %></td>
    <td><%= link_to 'Edit', edit_admin_town_path(admin_town) %></td>
    <td><%= link_to 'Destroy', admin_town, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Town', new_admin_town_path %>

app/views/admin/towns/new.html.erb
<h1>New admin_town</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_towns_path %>

app/views/admin/towns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Town:</b>
  <%= @admin_town.town %>
</p>


<%= link_to 'Edit', edit_admin_town_path(@admin_town) %> |
<%= link_to 'Back', admin_towns_path %>