config/routes.rb
Rails3::Application.routes.draw do

  resources :personaldatas

  resources :months

  resources :products

  resources :calls

  resources :standared_visits

  resources :msrplanners

  resources :tour_programs

  resources :headquators

  resources :places

  namespace :admin do resources :classifydoctors end

  resources :classifydoctors

  resources :doctors

  resources :towns

  namespace :admin do resources :doctors end

  namespace :admin do resources :towns end

  get "about/index"

  namespace :admin do resources :companies end

  devise_for :users, :controllers => { :sessions => "user_sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles

  resources :users do
     member do
       get :edit_password 
       get :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end

  resources :announcements
  
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    resources :settings 
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }
    resources :announcements
    resources :commits
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email        
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end
  end
  

  root :to => "dashboard#index"
  

end

app/models/standared_visit.rb
class StandaredVisit < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :doctor
  belongs_to :doctor
  belongs_to :call
  belongs_to :product
  belongs_to :product
  belongs_to :product
  belongs_to :month
end

app/controllers/standared_visits_controller.rb
class StandaredVisitsController < ApplicationController
  # GET /standared_visits
  # GET /standared_visits.xml
  def index
    @standared_visits = StandaredVisit.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @standared_visits }
    end
  end

  # GET /standared_visits/1
  # GET /standared_visits/1.xml
  def show
    @standared_visit = StandaredVisit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @standared_visit }
    end
  end

  # GET /standared_visits/new
  # GET /standared_visits/new.xml
  def new
    @standared_visit = StandaredVisit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @standared_visit }
    end
  end

  # GET /standared_visits/1/edit
  def edit
    @standared_visit = StandaredVisit.find(params[:id])
  end

  # POST /standared_visits
  # POST /standared_visits.xml
  def create
    @standared_visit = StandaredVisit.new(params[:standared_visit])

    respond_to do |format|
      if @standared_visit.save
        format.html { redirect_to(@standared_visit, :notice => 'Standared visit was successfully created.') }
        format.xml  { render :xml => @standared_visit, :status => :created, :location => @standared_visit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @standared_visit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /standared_visits/1
  # PUT /standared_visits/1.xml
  def update
    @standared_visit = StandaredVisit.find(params[:id])

    respond_to do |format|
      if @standared_visit.update_attributes(params[:standared_visit])
        format.html { redirect_to(@standared_visit, :notice => 'Standared visit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @standared_visit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /standared_visits/1
  # DELETE /standared_visits/1.xml
  def destroy
    @standared_visit = StandaredVisit.find(params[:id])
    @standared_visit.destroy

    respond_to do |format|
      format.html { redirect_to(standared_visits_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/standared_visits_helper.rb
module StandaredVisitsHelper
end

app/views/standared_visits/_form.html.erb
<%= form_for(@standared_visit) do |f| %>
  <% if @standared_visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@standared_visit.errors.count, "error") %> prohibited this standared_visit from being saved:</h2>

      <ul>
      <% @standared_visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :doctor, 'Doctor Name' %><br />
    <%= f.collection_select :doctor_id, Doctor.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :doctor, 'Doctor Address' %><br />
    <%= f.collection_select :doctor_id, Doctor.all, :id, :address %>
  </div>
  <div class="field">
    <%= f.label :doctor, 'Doctor Type' %><br />
    <%= f.collection_select :doctor_id, Doctor.all, :id, :doctor_type %>
  </div>
  <div class="field">
    <%= f.label :call, 'Type of Call' %><br />
    <%= f.collection_select :call_id, Call.all, :id, :type_of_call %>
  </div>
  <div class="field">
    <%= f.label :product,'Product 1 ' %><br />
    <%= f.collection_select :product_id, Product.all, :id, :pname %>
  </div>
  <div class="field">
    <%= f.label :product,'Product 2' %><br />
    <%= f.collection_select :product_id, Product.all, :id, :pname %>
  </div>
  <div class="field">
    <%= f.label :product,'Product 3' %><br />
    <%= f.collection_select :product_id, Product.all, :id, :pname %>
  </div>
  <div class="field">
    <%= f.label :month %><br />
    <%= f.collection_select :month_id, Month.all, :id, :month %>
  </div>
  <div class="field">
    <%= f.label :amc %><br />
    <%= f.text_field :amc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/standared_visits/edit.html.erb
<h1>Editing standared_visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @standared_visit %> |
<%= link_to 'Back', standared_visits_path %>

app/views/standared_visits/index.html.erb
<h1>Listing standared_visits</h1>

<table>
  <tr>
    <th>Doctor</th>
    <th>Doctor</th>
    <th>Doctor</th>
    <th>Call</th>
    <th>Product</th>
    <th>Product</th>
    <th>Product</th>
    <th>Month</th>
    <th>Amc</th>
    <th></th>
    <th></th>
  </tr>

<% @standared_visits.each do |standared_visit| %>
  <tr>
    <td><%= standared_visit.doctor.name %></td>
    <td><%= standared_visit.doctor.address %></td>
    <td><%= standared_visit.doctor.doctor_type %></td>
    <td><%= standared_visit.call %></td>
    <td><%= standared_visit.product %></td>
    <td><%= standared_visit.product %></td>
    <td><%= standared_visit.product %></td>
    <td><%= standared_visit.month.month %></td>
    <td><%= standared_visit.amc %></td>
    <td><%= link_to 'Show', standared_visit %></td>
    <td><%= link_to 'Edit', edit_standared_visit_path(standared_visit) %></td>
    <td><%= link_to 'Destroy', standared_visit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Standared visit', new_standared_visit_path %>

app/views/standared_visits/new.html.erb
<h1>New standared_visit</h1>

<%= render 'form' %>

<%= link_to 'Back', standared_visits_path %>

app/views/standared_visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Doctor Name:</b>
  <%= @standared_visit.doctor.name %>
</p>

<p>
  <b>Doctor Address:</b>
  <%= @standared_visit.doctor.address %>
</p>

<p>
  <b>Doctor Type:</b>
  <%= @standared_visit.doctor.doctor_type %>
</p>

<p>
  <b>Type of Call:</b>
  <%= @standared_visit.call.type_of_call %>
</p>

<p>
  <b>Product 1:</b>
  <%= @standared_visit.product.pname %>
</p>

<p>
  <b>Product 2:</b>
  <%= @standared_visit.product.pname %>
</p>

<p>
  <b>Product 3:</b>
  <%= @standared_visit.product.pname %>
</p>

<p>
  <b>Month:</b>
  <%= @standared_visit.month.month %>
</p>

<p>
  <b>Amc:</b>
  <%= @standared_visit.amc %>
</p>


<%= link_to 'Edit', edit_standared_visit_path(@standared_visit) %> |
<%= link_to 'Back', standared_visits_path %>